- apps/src/lib.rs
I'm not entirely sure what caused this but every half hour or so line 152 of apps/src/lib.rs would cause the main thread to panic. In that case, just remove the offending aircraft from the list instead of crashing.
> fixed occasional panic of AirplaneState.last_time.elapsed().unwrap()

- .github/workflows/binaries.yml
- .github/workflows/main.yml
Add release binaries for arm and linux targets on master branch pushes
or releases
Use nightly for clippy
Closes #35
> Add ARM ci/release binaries

- README.md
- apps/README.md
- apps/src/radar.rs
As discussed in #62, rename `cities` as `locations` in the radar application. I myself use this to show airports, so this is way more accurate even in my own use case.
> feat: rename radar `--cities` as `--locations`

- apps/README.md
Move key/mouse bindings header to be under the `radar` application.
Add the keybinding `q` for quitting the application
Closes #63
> feat: update readme for apps

- apps/Cargo.toml
- apps/README.md
- apps/src/radar.rs
Respect terminal width when outputting the `--help` usage.
Add context to what gpsd means
> feat: use clap wrap_help

- src/cpr.rs
If the `m` value in the CPR calculation works out to be negative the use
of `%` results in an incorrect (negative) value.
This commit uses `rem_euclid` instead of `%` to get the expected value
when calculating longitude (at least for the test input used and within
a few decimal places).
I'm not entirely sure that `rem_euclid` is the correct replacement but
from the little bit of reading I've done to refresh myself on modulus
and related math I think it is suitable (plus the existing test suite
still passes in addtion to the new test for this case).
Example Rust code to show differences:
#![allow(unused)]
fn main() {
let ni = 47.0;
let m: f64 = -28.0;
println!("ni = {}", ni);
println!("m = {}", m);
println!("m % ni = {}", (m % ni));
println!("m.rem_euclid(ni) = {}", m.rem_euclid(ni));
} …
> Handle negative `m` value

- apps/README.md
- apps/src/lib.rs
- apps/src/radar.rs
Since we ignore all other messages, limit our reading of the frames by
first checking for the 17 in the first 5 bits of the byte array
> feat: add --limit-parsing to limit frames to ADSB

- apps/src/radar.rs
Log ADSB data just as dump1090 does, in our log file instead of using
derieved Debug fmt
> feat: use fmt::Display for logging

- .github/workflows/main.yml
- apps/src/radar.rs
Remove checking the lat_long_mutated inside the gpsd reading thread.
This doens't need to be read there, and should be read from just when
checking the new value from that thread. This was also renamed to
cstom_lat_long and switched to just a bool
> fix: fix moving lat/lon while in gpsd mode

- CHANGELOG.md
- Cargo.lock
- apps/README.md
- apps/src/lib.rs
- apps/src/radar.rs
- libadsb_deku/src/cpr.rs
Add range check from either the --lat and --long, or from --gpsd if
supplied. This limits the messages from being used in an aircrafts new
lat/long postion using the haversine distance from the reciever/operator
position.
Add distance check from the last aircraft position recorded. this
removes aircraft that are going physical impossible speeds based upon
the distance and the last time they were seen.
Add distance to Airplanes tab
Reduce time till dropped message to 30 seconds
Closes #21
> Add range and distance check

- README.md
Noticed a small typo in the README.   'quistart' should be 'quickstart'
> Fix typo, "quickstart"

- apps/src/radar.rs
After closing the program (with either `q` or `Control + C`) the terminal would print the mouse escape codes on all mouse movements (example below).
I was able to fix it by disabling mouse events capturing on program quit.
I think it fixes #116.
The other commit just adds a `#[rustfmt::skip]` attribute, as rustfmt didn't like the aligned equal signs in that enum and it would break them.
> fix: terminal prints mouse escape codes after closing radar

- apps/src/radar.rs
I think this was caused by not running the nightly rust fmt
> chore: remove rust fmt skip

- apps/src/cli.rs
- apps/src/lib.rs
- apps/src/radar.rs
* Add `heading` to Airplanes
* Add heading angles to aircraft in the `Map` view! Now you can correctly know what direction an aircraft is flying in!
* Add `--disable-icao` for **not** showing ICAO information for every aircraft
* Add `--disable-heading` for **not** showing the new heading angles
> Add heading graphics to `Map` view

- Cargo.lock
- apps/Cargo.toml
- apps/src/radar.rs
Remove chrono, they seem to have no interest in fixing the issue from:
https://rustsec.org/advisories/RUSTSEC-2020-0071.html.
This defers that issue by using the time crate directly and using the
local_offset functions from a single thread. (This uses localtime_r
locally)
> feat: remove chrono crate and use time

- apps/README.md
- apps/src/airport.rs
- apps/src/radar.rs
- ensure_no_std/Cargo.lock
- ensure_no_std/src/bin/main.rs
- libadsb_deku/src/adsb.rs
- libadsb_deku/src/lib.rs
- libadsb_deku/tests/test.rs
- rsadsb_common/src/lib.rs
Reduce the size of types to reduce memory usage of application and
library for embeded environs.
struct Altitude::alt has been changed to an Option<u16>. The change from
u32 to u16 was done for size reasons, and a normal operating altitude is
lower then the max u16. The Option was to fix the function returning 0
when it's actually a very invalid altitude.
AC13Field altitude was changed to a u16, this isn't usually a user
facing struct.
In libadsb_common, AirplaneDetails altitude was changed to u16, heading
was changed to f32. num_messages was changed to u32.
> General updates

- CHANGELOG.md
- apps/src/cli.rs
- apps/src/radar.rs
Add --retry-tcp for connecting to a dump1090 instance if that service
goes down.
The init_tcp_reader is used for the initial connection, which adds a tui
display for waiting for the connection which is nice. This same tui
display is shown when the server goes down and we try again.
QuitReason has been added for some better exit reasons
> Add --retry-tcp for retry for dump1090 connection

- apps/src/radar.rs
For small displays the year is not required. Kudos if you run this
application for that long and need the stats :)
> Remove year in stats Datetime

- apps/Cargo.toml
Remove features that are enabled by default in adsb_deku when std and
alloc are enabled by default and is always enabled in apps/
> Remove features in apps/

- libadsb_deku/src/adsb.rs
- libadsb_deku/src/bds.rs
Avoid read cycles and storage by just using the deku feature of writing
empty bits, storing no information and no reading of the data for
reserved fields that are unneeded.
> Use padding feature of deku to avoid reading

- CHANGELOG.md
- apps/src/radar/radar.rs
- apps/src/radar/stats.rs
- rsadsb_common/src/lib.rs
* Added total airplanes tracked. This is all airplanes that were added,
which does include airplanes that were removed and and then added
later, but it works
* Moved Stats to src/stats.rs
* common::action() now returns if an Airplane was added or not as the
Added enum
* Added tracing::info: "info!("[{icao}] now tracking");", when airplane
is first tracked
> Add total airplanes tracked to Stats page

- apps/README.md
- apps/src/radar/cli.rs
- apps/src/radar/help.rs
- apps/src/radar/map.rs
- apps/src/radar/radar.rs
- libadsb_deku/src/adsb.rs
Add display of callsign instead of only showing ICAO hex values. This
can also be controlled from the command line using --display-callsign
> Display Callsign in Map view

- apps/src/radar/cli.rs
- apps/src/radar/radar.rs
- rsadsb_common/README.md
- rsadsb_common/src/lib.rs
resolves #147 
Updated clap opts to have a flag with a default of `500`. Pass the `max_range` to where it is needed.
> Max range issue 147

- CHANGELOG.md
- Cargo.lock
- README.md
- apps/Cargo.toml
- apps/README.md
- apps/src/radar/cli.rs
- apps/src/radar/help.rs
- apps/src/radar/map.rs
- apps/src/radar/radar.rs
- libadsb_deku/Cargo.toml
- rsadsb_common/Cargo.toml
* --display-callsign not does the exact inverse of what it used to, and
now only displays the display of the callsign instead of the ICAO.
* use clap::AppSettings::DeriveDisplayOrder to show --help and -h in the
same order of the arguments in my definition
* update versions in readme to v0.6.1
> Refactor display to disable callsign

- libadsb_deku/src/adsb.rs
- libadsb_deku/src/lib.rs
Deku does the compare one at a time starting with the top item, give about a 3% performance boost if the most common are moved to the top.
> Move most used fields in enum to top

- Cargo.lock
- libadsb_deku/Cargo.toml
- libadsb_deku/src/adsb.rs
- libadsb_deku/src/lib.rs
See https://github.com/sharksforarms/deku/pull/246
Currently seeing some serious performance regressions:
```
lax_messsages           time:   [1.5287 s 1.5305 s 1.5330 s]
change: [+56.845% +57.120% +57.449%] (p = 0.00 < 0.05)
Performance has regressed.
Found 12 outliers among 100 measurements (12.00%)
1 (1.00%) low severe
5 (5.00%) low mild
5 (5.00%) high mild
1 (1.00%) high severe
```
> Update deku to bitvec 1.0

- Cargo.lock
- apps/src/1090/1090.rs
- apps/src/radar/radar.rs
- ensure_no_std/Cargo.lock
- ensure_no_std/src/bin/main.rs
- libadsb_deku/Cargo.toml
- libadsb_deku/README.md
- libadsb_deku/benches/decoding.rs
- libadsb_deku/src/adsb.rs
- libadsb_deku/src/bds.rs
- libadsb_deku/src/lib.rs
- libadsb_deku/tests/file.rs
- libadsb_deku/tests/test.rs
* Remove the use of deku's own from_bytes, instead write our own that
doesn't allow bit offsets. Also add our own from_reader.
* Update deku to 0.18.1, adding seek to a ton of internal buffers and
updating checksum code to support a checksum calculation during Read and
Seek.
* Change Comm-D into ModeS Extended Squitter to be more correct for those
DF calculations
* Remove re-export of deku, sa it's not needed
* Disable test testing_surveillanceidentityreply_err, as it was causing
issues with endian-ness, so I think it's a bad test. (Other AC13Altitude test were passing)
> Update to deku 0.18.0
